resources:
  repositories:
  - repository: wire-ios-shared-resources
    type: github
    name: wireapp/wire-ios-shared-resources
    ref: refs/heads/feature/ipa-build # Branch to fetch the jobs template from 
    endpoint: wireapp

trigger:
  branches:
    include:
      - develop

jobs:
  - template: Azure/ui-pipelines.yml@wire-ios-shared-resources
